repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix"]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-merge-conflict
      - id: check-executables-have-shebangs

  - repo: local
    hooks:
      - id: uv_lock
        name: Ensure dependency lock files are up-to-date
        entry: uv lock
        language: system
        types: [python]
        pass_filenames: false
      - id: ruff_lint
        name: Lint Python code using Ruff
        entry: uv run ruff check --fix
        language: system
        types: [python]
        pass_filenames: false
      - id: ruff_format
        name: Format Python code using Ruff
        entry: uv run ruff format .
        language: system
        types: [python]
        pass_filenames: false
      - id: mypy
        name: Perform static type checking using MyPy
        entry: uv run mypy . --explicit-package-bases
        language: system
        types: [python]
        pass_filenames: false
