steps:

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-kfp-component'
    args:
      - 'build'
      - '--file'
      - 'Dockerfile-kfp'
      - '--tag'
      - 'europe-west2-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/kfp-component:${_USER}-latest'
      - '--target'
      - 'base'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - '--cache-from'
      - 'europe-west2-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/kfp-component:${_USER}-latest'
      - '.'
    env:
      - 'DOCKER_BUILDKIT=1'
      - 'COMPOSE_DOCKER_CLI_BUILD=1'

images: ['europe-west2-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/kfp-component:${_USER}-latest']

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
