name: "CICD"

on:
  pull_request:
    branches: [ '**' ]
  push:
    branches: [ 'main' ]

jobs:
  lint_and_test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.6"
      - name: "Sync dependencies"
        run: uv sync
      - name: "Run linting"
        run: uv run ruff check --fix .
      - name: "Run formatting"
        run: uv run ruff format .
      - name: "Run static type checking"
        run: uv run mypy . --explicit-package-bases
      - name: "Run unit tests"
        run: uv run pytest
